VALIDAITON_REQUIRED_FIELD = "This field is required."
VALIDATION_CATEGORY_OWNER = "You are not the owner of this category."
VALIDATION_GOAL_OWNER = "You are not the owner of this goal."
VALIDATION_NOT_ALLOWED_FOR_DELETED_CATEGORY = "Not allowed for deleted category"
VALIDATION_CATEGORY_NOT_FOUND = "Category not found"
VALIDATION_NOT_ALLOWED_FOR_DELETED_GOAL = "Not allowed for deleted goal"