# Generated by Django 4.2 on 2023-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60),
        ),
    ]
