# Generated by Django 4.2 on 2023-05-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goal_created_at_alter_goal_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='goalcategory',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='goalcategory',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='goalcomment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='goalcomment',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
