# Generated by Django 4.2 on 2023-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_rename_created_at_goal_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
