# Generated by Django 4.2 on 2023-05-04 07:21

from django.db import migrations, transaction

def create_objects(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    GoalCategory = apps.get_model('goals', 'GoalCategory')

    with transaction.atomic():
        for user in User.objects.all():
            new_board = Board.objects.create(
                title="Мои цели"
            )

            BoardParticipant.objects.create(
                board=new_board,
                user=user
            )

            GoalCategory.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
