# Generated by Django 4.2.1 on 2023-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
