version: "3.9"
services:
  api: 
    container_name: todolist_back
    image: ykorolikhin/todolist_django:main
    restart: always
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    
  db:
    ports:
      - 5433:5432
    restart: always
    container_name: todolist_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - v-todolist-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  front: 
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 80:80
    container_name: todolist_front
    restart: always
    networks:
      - backend
    depends_on:
      - api

  
volumes:
  v-todolist-db:

networks:
  backend:
    driver: bridge