# Generated by Django 4.2.1 on 2023-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('tg_chat_id', models.BigIntegerField(verbose_name='tg chat id')),
                ('username', models.CharField(default=None, max_length=512, null=True)),
            ],
        ),
    ]
