name: Build and deploy

on:
  push:
    branches:
      - 'main'
env:
  DJANGO_SECRET_KEY:  ${{secrets.DJANGO_SECRET_KEY}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  POSTGRES_USER:  ${{secrets.POSTGRES_USER}} 
  POSTGRES_PASSWORD:  ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_DB:  ${{secrets.POSTGRES_DB}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/todolist_django
      - name: Login to Docker
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
        
      - name: Build and Push
        uses: docker/build-push-action@v3
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          source: "deploy/docker-compose.yml"
          target: "todolist"
          strip_components: 1

      - name: deploy app
        uses: appleboy/ssh-action@master
        env:
          DJANGO_SECRET_KEY:  ${{secrets.DJANGO_SECRET_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          POSTGRES_USER:  ${{secrets.POSTGRES_USER}} 
          POSTGRES_PASSWORD:  ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB:  ${{secrets.POSTGRES_DB}}
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          envs: DJANGO_SECRET_KEY,DATABASE_URL, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
          script: |
            cd todolist
            touch .env
            echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" >> .env
            echo "DATABASE_URL=$DATABASE_URL" >> .env
            echo "POSTGRES_USER=$POSTGRES_USER" >> .env
            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
            echo "POSTGRES_DB=$POSTGRES_DB" >> .env
            docker system prune -f 
            docker compose up -d

        
  

