name: Build and deploy

on:
  push:
    branches:
      - 'main'
env:
  DOCKER_COMPOSE_FILE: docker-compose.yml
  DJANGO_SECRET_KEY:  ${{secrets.DJANGO_SECRET_KEY}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  POSTGRES_USER:  ${{secrets.POSTGRES_USER}} 
  POSTGRES_PASSWORD:  ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_DB:  ${{secrets.POSTGRES_DB}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/todolist_django
      - name: Login to Docker
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Push
        uses: docker/build-push-action@v3
        with: 
          context: .
          file: docker-compose.yml
          push: true
          tags: ${{ steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

        
  

